#!/bin/bash

if [[ $1 == "kill" ]]; then
    killall -u media lighttpd
    for host in ${HOSTS[@]}; do
        ssh $host -O exit
    done
else
    if mpc -q >/dev/null 2>&1 then; else
        echo "E MPD not running"
        echo "  Start MPD before starting Movie-Server"
        exit 1
    fi


    for host in ${HOSTS[@]}; do
        ssh $host -MN &disown
    done
    lighttpd -f lighttpd.conf
fi
